
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    type: rest
    resource: AppBundle\Controller\UserController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
